version: "3.8"

networks:
  default:
    name: unifi

volumes:
  mongodb:
    name: unifi-mongodb
  controller:
    name: unifi-controller

services:

  mongodb:
    image: mongo:5.0
    container_name: unifi-mongodb
    volumes:
      # MongoDB storage volume
      - type: volume
        source: mongodb
        target: /data/db
      # MongoDB init scripts
      - type: bind
        read_only: true
        source: ./01-admin.sh
        target: /docker-entrypoint-initdb.d/01-admin.sh
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-admin}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-unifi}
      # Not used by the MongoDB image but our custom init scripts
      MONGO_DB_USER: ${MONGO_DB_USER:-unifi}
      MONGO_DB_PASS: ${MONGO_DB_PASS:-unifi}

  controller:
    depends_on:
      - mongodb
    image: ghcr.io/stellirin/unifi-controller:${CONTROLLER_IMAGE_TAG:-latest}
    container_name: unifi-controller
    ports:
      - "1900:1900/udp"
      - "3478:3478/udp"
      - "6789:6789/tcp"
      - "8080:8080/tcp"
      - "8443:8443/tcp"
      - "8843:8843/tcp"
      - "8880:8880/tcp"
      - "10001:10001/udp"
    volumes:
      - type: volume
        source: controller
        target: /var/lib/unifi
    environment:
      MONGO_DB_HOST: ${MONGO_DB_HOST:-mongodb}
      MONGO_DB_PORT: ${MONGO_DB_PORT:-27017}
      MONGO_DB_USER: ${MONGO_DB_USER:-unifi}
      MONGO_DB_PASS: ${MONGO_DB_PASS:-unifi}
