apiVersion: v1
kind: Secret
metadata:
  namespace: unifi
  name: unifi-mongodb-admin-secret

data:
  # echo -n 'stuff' | base64
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4=

---

apiVersion: v1
kind: Secret
metadata:
  namespace: unifi
  name: unifi-mongodb-user-secret

data:
  # Not used by the MongoDB server but our custom init scripts
  MONGO_DB_USER: dW5pZmk=
  MONGO_DB_PASS: dW5pZmk=

---

apiVersion: v1
kind: Secret
metadata:
  namespace: unifi
  name: unifi-mongodb-keyfile-secret

data:
  # openssl rand -base64 756 | base64
  MONGODB_KEYFILE: eFZJcTBJaDBEWWNvTCtxNVlBeE5pWW8wNFMyZWVVWnJCUmJoSnpycFZhRXNoemVWNmNPcUFjVjZKVEFpbEdpUwpDRnJwOFRNK0JkZTE1YytVSVdJRWpvRWtxWjhWckV0UjJKTmpVbFNmSjlyWEs3VHh6WFhwVGt0dWVFd3BoOWxDCjdWMGswcWJjVmdyWkZQZWpiT05nS0ZLcnpzM3NyUm00c0tqdDNIVCtTM1haZ2pzZ0Z0VkduOEw0VUszTGlKYTkKNXdqWXA5dGp4VFc0V3JDRzJ3K2tiK3dJUEN5WVJNWm5JRVZYMFFaWVFWK3MwMWxFUVJjWFovWklnZWZEclBCUApFV1VCOFhlZmtVc2V6UFlrTmJubkRtc1JOaGhyaDJjNTdCRFArL2dwMmYyTXQyeGNza0FtdnhHbjYxQVBHbWdXCjA0QnNON3lveFduWkV4OTJVYTVydm9uN2l6bzF0bUVseWxPR3JBcU56d2VZSGNLeVRHQUdOeUpYTGJ1czVSNVIKenVTcy90V1BjeGtCaThIT1ppZGkvQmxGSEFmTG1TVmRZZDEwRjAzdEowQSsvZlpnL2FWYXBYUERodWIwUkFIMgpOd2FWZkNpVFRkL0owakZ2d0xkZEZWa2QzZDByVngrNUJCWnZIRldnN1l1UzI4SUxaWis5Tmdud1lLTEhXYXhqCkhvU3VNUTlDSUc3b2kyQzUrRHRqblBkTDJleUFoOFpkQ1F0bmFEendtcml1Rlg1NnM2ZVh1SEEyVVNMMml6VkEKS013cStpRkVXQnUxNlRPSXkyVFlzaHJndnJzMGpwenJNNHk2VUt3L1d4dVEwbmtYeExEUUpuSGphVUpSNzRJVQorUXZuM05Fa1RuZlVGcHpYTHhwejdPZDllUzh0cFJ6SHZuNUo1QU9rRFNRREhlRVQvOXBFYWFVbXVpajJ1Sk5ZCnVjWGwyKzdVYTEyeEVRVnY4NVdKWnFmTnY2eEF5NW54ei96Z2lqOUR1VUFkUmRYUUh0djNPeEp5UXlWb2hqL3gKQjVsM3E5aHRxMGl3dHRta1o5SG0rV3FjbmpkbSs2S1l1RGdETzdhaGtDRm8xREhoODU4OXY4SFRVOGF0dkNqagpSOE02UmhuekZ5MnE5aHNEd2U4ZmlTN3I0UjAyNUdNOVMrWFlDeldsTzJpQWxRQTg1TlV6YnlUOTB1Z2N1TERVCmtJUzlaTmVPTE0zZy9CdHcxSVkwckJNcmJxN1lPb1dCbXVuQXFSRDhMYjY4OEsxNkI4ZGZFWHNVcjEwWUs3VzIKMUkzQWtuUnBPczNqSFNSZkp0eTJBUmF5ZG93YW8zekxxMHR6Nm8rYWRmVk5uZkQ1Cg==
