apiVersion: v1
kind: ConfigMap
metadata:
  namespace: unifi
  name: unifi-mongodb-configmap

data:
  MONGO_INITDB_DATABASE: "unifi"
  MONGO_INITDB_ROOT_USERNAME_FILE: "/run/secrets/mongodb/MONGO_INITDB_ROOT_USERNAME"
  MONGO_INITDB_ROOT_PASSWORD_FILE: "/run/secrets/mongodb/MONGO_INITDB_ROOT_PASSWORD"

  MONGO_DB_USER_FILE: "/run/secrets/mongodb/MONGO_DB_USER"
  MONGO_DB_PASS_FILE: "/run/secrets/mongodb/MONGO_DB_PASS"
  MONGODB_KEYFILE_FILE: "/run/secrets/mongodb/MONGODB_KEYFILE"
