apiVersion: v1
kind: Service
metadata:
  namespace: unifi
  name: mongodb
  labels:
    app: mongodb

spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
    targetPort: mongo
