apiVersion: batch/v1
kind: Job
metadata:
  namespace: unifi
  name: mongodb-replicaset-initiate

spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: mongo-rs
          image: mongo:4.0
          command: [
            "/entrypoint.sh",
          ]
          envFrom:
            - configMapRef:
                name: unifi-mongodb-configmap
          volumeMounts:
            # MongoDB credentials
            - name: credentials
              mountPath: /run/secrets/mongodb
            # MongoDB init scripts
            - name: initdb
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh

      volumes:
        # MongoDB credentials
        - name: credentials
          secret:
            secretName: unifi-mongodb-admin-secret
            defaultMode: 0444
            items:
              - key:  MONGO_INITDB_ROOT_USERNAME
                path: MONGO_INITDB_ROOT_USERNAME
              - key:  MONGO_INITDB_ROOT_PASSWORD
                path: MONGO_INITDB_ROOT_PASSWORD

        # MongoDB init scripts
        - name: initdb
          configMap:
            name: unifi-mongodb-replicaset-configmap
            defaultMode: 0555
            items:
              - key: ENTRYPOINT_RS_SH
                path: entrypoint.sh
