apiVersion: v1
kind: ConfigMap
metadata:
  namespace: unifi
  name: unifi-controller-configmap

data:
  MONGO_DB_NAME: "unifi"
  MONGO_DB_HOST: "mongodb"
  MONGO_DB_PORT: "27017"
  MONGO_DB_USER_FILE: "/run/secrets/mongodb/MONGO_DB_USER"
  MONGO_DB_PASS_FILE: "/run/secrets/mongodb/MONGO_DB_PASS"
