apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: unifi
  name: mongodb-4.4
  labels:
    app: mongodb

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb

  template:
    metadata:
      labels:
        app: mongodb
    spec:

      initContainers:
        - name: mongo-init
          image: mongo:4.4
          imagePullPolicy: Always
          command: [
            "/entrypoint.sh",
          ]
          args: [
            "mongod",
          ]
          envFrom:
            - configMapRef:
                name: unifi-mongodb-configmap
          volumeMounts:
            # MongoDB credentials
            - name: credentials
              mountPath: /run/secrets/mongodb
            # MongoDB init scripts
            - name: initdb
              mountPath: /docker-entrypoint-initdb.d/01-admin.sh
              subPath: 01-admin.sh
            - name: initdb
              mountPath: /entrypoint.sh
              subPath: entrypoint.sh
            # MongoDB storage volume
            - name: data
              mountPath: /data/db

      containers:
        - name: mongo
          image: mongo:4.4
          imagePullPolicy: Always
          args: [
            "mongod",
            "--bind_ip_all"
          ]
          ports:
            - name: mongo
              containerPort: 27017
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - pgrep
                - mongod
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          volumeMounts:
            # MongoDB storage volume
            - name: data
              mountPath: /data/db
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 1Gi

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mongodb-4.4-pvc
        # MongoDB credentials
        - name: credentials
          projected:
            defaultMode: 0444
            sources:
              - secret:
                  name: unifi-mongodb-admin-secret
                  items:
                    - key:  MONGO_INITDB_ROOT_USERNAME
                      path: MONGO_INITDB_ROOT_USERNAME
                    - key:  MONGO_INITDB_ROOT_PASSWORD
                      path: MONGO_INITDB_ROOT_PASSWORD
              - secret:
                  name: unifi-mongodb-user-secret
                  items:
                    - key:  MONGO_DB_USER
                      path: MONGO_DB_USER
                    - key:  MONGO_DB_PASS
                      path: MONGO_DB_PASS

        # MongoDB init scripts
        - name: initdb
          configMap:
            name: unifi-mongodb-initdb-configmap
            defaultMode: 0555
            items:
              - key: 01_ADMIN_SH
                path: 01-admin.sh
              - key: ENTRYPOINT_INIT_SH
                path: entrypoint.sh
