#!/bin/bash

# Tag and push image for each additional tag
for TAG in `git tag -l --points-at HEAD`
do
    UIVER=(${TAG//./ })

    docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${TAG}
    docker tag ${IMAGE_NAME} ${DOCKER_REPO}:${UIVER[0]}.${UIVER[1]}
    docker tag ${IMAGE_NAME} ${DOCKER_REPO}:stable
    docker push ${DOCKER_REPO}:${TAG}
    docker push ${DOCKER_REPO}:${UIVER[0]}.${UIVER[1]}
    docker push ${DOCKER_REPO}:stable
done
